### ISSUE TITLE
RTL not supported in Sphinx flask theme

### ISSUE THREAD

**Issue by mmdbalkhi** [flaskcwg/translation-coordination#9]
## RTL not supported in Sphinx flask theme

Persian is an RTL language, but the theme of the flask is LTL and it shows the Persian text badly. How can I solve this problem?

-------
![now](https://user-images.githubusercontent.com/65954744/145348481-054852b0-d11f-4ae6-895c-8fc9504ad3c7.png)
This is how it is now
-------
![this](https://user-images.githubusercontent.com/65954744/145349426-e1188925-a59b-4288-973b-7854668856d5.png)
But it has to be this way
-------

Related to issue #8

**Comment by greyli** [comment]
How do you achieve the second screenshot?

Some references:

- A Sphinx theme that supports RTL: [Minoo](https://github.com/saeiddrv/SphinxMinooTheme)
- A related [SO question](https://stackoverflow.com/q/12661206/5511849).

**Comment by mmdbalkhi** [comment]
> How do you achieve the second screenshot?

By editing HTML in the browser

There is a problem. The flask theme should have this feature. The default theme written in the conf.py file is  Flask and we can not use the new theme because it conflicts with the flask theme.

**Comment by mmdbalkhi** [comment]
# The problem was solved

Sorry, the problem was me. I should make a custom CSS and write to conf.py to sphinx use this CSS file.
